[server_config]
domain = "jahziel.xyz"
pfx = "/home/hapax/code/titan/jahzielxyz.pfx"

[routes]
"/" = "index.gemini" # /
"/about" = "about.gemini" # /about
"/who/ami" = "jahziel.gemini" # /who/ami
"/download" = "/home/hapax/code/download.txt"
